# Generated by Django 2.0.2 on 2018-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField(auto_now_add=True)),
                ('closing_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
