# Generated by Django 2.0.2 on 2018-02-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img_url',
            field=models.URLField(default='whatever.ccom'),
            preserve_default=False,
        ),
    ]
